### PR TITLE
Added Sentry.

### PR DESCRIPTION
**Pull request by dblock**
I already configured the DSNs in both production and staging.

Should I be removing NR?

### CODE REVIEW

**Comment by dblock** [comment]
Since @sweir27 is OOO -> @yuki24

**Comment by yuki24** [comment]
👍 looks good to me!

**Comment by dblock** [comment]
@yuki24 Should I be removing NR from here?

**Comment by yuki24** [comment]
I don't think so. NR is more like a performance monitoring tool while Sentry is an error reporting service. They don't overlap and are both useful.

**Comment by dblock** [comment]
Proof that it worked, https://sentry.io/artsynet/doppler-production/issues/455180697/

**Pull request merged**
